1. Convert List to 1D Array

In [ ]:
import numpy as np

my_list=[12.23, 13.32, 100, 36.32]

arr=np.array(my_list)

print(arr)

<class 'numpy.ndarray'>


2. Create 3x3 Matrix (2?10)

In [4]:
import numpy as np

arr=np.arange(2,11,1)
shape=arr.reshape(3,3)
print(shape)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. Null Vector (10) & Update Sixth Value

In [7]:
import numpy as np

arr=np.zeros((1,10))

arr[0,6]=11

print(arr)

[[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]]


4. Array from 12 to 38

In [9]:
import numpy as np

arr=np.arange(12,38,1)

print(arr)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


5. Convert Array to Float Type

In [14]:
import numpy as np

arr=np.array([1, 2, 3, 4],dtype=float)

print(arr)

print("dtype:",arr.dtype)


[1. 2. 3. 4.]
dtype: float64


6. Celsius to Fahrenheit Conversion

In [32]:
import numpy as np

# Boshlang'ich massiv (Celsius)
celsius = np.array([0, 12, 45.21, 34, 99.91, 32])

# Celsius -> Fahrenheit
fahrenheit = (celsius * 9/5) + 32

# Fahrenheit -> Celsius
c_back = (fahrenheit - 32) * 5/9

print("Values in Celsius degrees:", celsius)
print("Values in Fahrenheit degrees:", fahrenheit)
print("Back to Celsius:", c_back)


Values in Celsius degrees: [ 0.   12.   45.21 34.   99.91 32.  ]
Values in Fahrenheit degrees: [ 32.     53.6   113.378  93.2   211.838  89.6  ]
Back to Celsius: [ 0.   12.   45.21 34.   99.91 32.  ]


7. Append Values to Array (Do self-tudy)

In [34]:
import numpy as np

arr=([10,20,30])
new_arr=np.append(arr,[40,50,60,70,80,90])

print(new_arr)

[10 20 30 40 50 60 70 80 90]


8. Array Statistical Functions (Do self-tudy)

In [ ]:
import numpy as np

arr=np.random.rand(10)
print(arr)
print("The mean of array:",arr.mean())
print("The mediana of array:",np.median(arr))
print("The  standard deviation of the array:",arr.std())

[0.06962989 0.39356605 0.69561383 0.71848051 0.35392011 0.99324358
 0.54414691 0.37752284 0.78738232 0.18098994]
The mean of array: 0.5114495983717751
The mediana of array: 0.4688564798753223
The  standard deviation of the array: 0.27334380795998314


9 Find min and max

In [27]:
import numpy as np

arr=np.random.randint(1,100,size=(10,10))
print(arr)
print("Max:",arr.max())
print("Min:",arr.min())

[[59 25 77 91 42 34 14  1 46  4]
 [28 52 48 61  5 92  5 46 25  8]
 [ 7 66 85 40 70 18 36 93 60  9]
 [46 99 70 21 42 76 52 54  2  2]
 [91 31  5 96 24 28 22 32 53  9]
 [54 81 39 92  3 20 68  6 22 52]
 [97 30 59 34 58 99 93 45 13 26]
 [24  6 56 99 37 43 35 82 56 88]
 [48 43 39 17 45 27 64 13 72 70]
 [56 41 68 10 16 79 93 79 40 86]]
Max: 99
Min: 1


10.Create a 3x3x3 array with random values.

In [29]:
import numpy as np

arr=np.random.randint(1,10,size=(3,3,3))

print(arr)

[[[1 1 3]
  [9 3 5]
  [1 5 3]]

 [[7 9 6]
  [3 4 7]
  [5 5 2]]

 [[8 7 9]
  [8 1 5]
  [3 8 6]]]
